---
# drone connection settings
drone:
  address: "192.168.1.1"
  navdata_port: 5554
  video_port: 5555
  command_port: 5556

# logging setup
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: ../logs/info.log
      maxBytes: 10485760 # 10MB
      backupCount: 10
      encoding: utf8

    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: simple
      filename: ../logs/errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 10
      encoding: utf8

  loggers:
    ARdrone-controller:
      level: INFO
      handlers: [console, info_file_handler, error_file_handler]
      qualname: ARdrone-controller
      propagate: no
    root:
      level: INFO
      handlers: [console, info_file_handler, error_file_handler]
