# drone connection settings
connection:
  iface: "enp0s8"
  src_ip: "192.168.1.3"
  dst_ip: "192.168.1.1"
  src_port: 5556
  dst_port: 5556
  src_mac: "dc:a9:04:7f:ed:94"
  dst_mac: "A0:14:3D:A5:85:2A"

# drone command payloads
commands:
  #  ATREF commands Controls the basic behaviour of the drone (take-off/landing, emergency stop/reset)
  AT_REF:
    takeoff: "AT*REF=<sequence-number>,290718208\r"
    land: "AT*REF=<sequence-number>,290717696\r"
    emergency: "AT*REF=<sequence-number>,290717952\r"
  AT_PCMD:
    tbd: ""
  AT_PCMD_MAG:
    tbd: ""
  AT_FTRIM:
    tbd: ""
  AT_CALIB:
    tbd: ""
  AT_CONFIG:
    tbd: ""
  AT_CONFIG_TDS:
    tbd: ""
  AT_COMWDG:
    tbd: ""

# logging setup
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
      simple:
          format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
      console:
          class: logging.StreamHandler
          level: DEBUG
          formatter: simple
          stream: ext://sys.stdout

      info_file_handler:
          class: logging.handlers.RotatingFileHandler
          level: INFO
          formatter: simple
          filename: logs/info.log
          maxBytes: 10485760 # 10MB
          backupCount: 10
          encoding: utf8

      error_file_handler:
          class: logging.handlers.RotatingFileHandler
          level: ERROR
          formatter: simple
          filename: logs/errors.log
          maxBytes: 10485760 # 10MB
          backupCount: 10
          encoding: utf8

  loggers:
      ARdrone-controller:
          level: INFO
          handlers: [console]
          qualname: ARdrone-controller
          propagate: no
  root:
      level: INFO
      handlers: [console, info_file_handler, error_file_handler]